#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server

# ./0-transfer_file some_page.html 8.8.8.8 sylvain /vagrant/private_key
# scp [options] source destination
# scp localfile.txt username@remote.server:/path/on/remote/server/
# localfile.txt: The file on your local machine.
# username: Your username on the remote server.
# remote.server: The address of the remote server.
# /path/on/remote/server/: The destination path on the remote server.
if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file_path=$1
	server_ip=$2
	username=$3
	path_to_ssh_key=$4

	scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$file_path" "$username@$server_ip":~/
fi
