#!/usr/bin/env bash
# a bash script that configures web-01 server to be identical to web-02 server

# update package
sudo apt-get update

# install nginx
sudo apt-get -y install nginx

# set custom header in nginx configuration file
sudo sed -i "/server_name _;/a\ \ \ \ \ \ \ \ add_header X-Served-By ${hostname};" "$nginx_conf"

# restart nginx
sudo service nginx restart
