#!/usr/bin/env bash
# deamon process.
if [ "$1" = "start" ]
then
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" = "stop" ]
then
	pkill -f ./manage_my_process
	rm  "/var/run/my_process.pid"
	echo "manage_my_process stopped"
elif [ "$1" = "restart" ]
then
	# pkill -P $(cat "/var/run/my_process.pid")
	pkill -f ./manage_my_process
	rm  "/var/run/my_process.pid"
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
