#!/usr/bin/env bash
# scripts that that displays the content of the file /etc/passwd.
# The script should only display username, user id, Home directory path for the user
# Only while loop can be used
while IFS=: read -r username _ userid _ _ home _;
do
	echo "$username:$userid:$home"
done < /etc/passwd
