#!/usr/bin/env bash
# script that displays the visitor IP along with the HTTP status code from the Apache log file
# awk '{print ++counter, $1, $9}' counter=0 apache-access.log
awk '{
    key = $1 " " $9
    occurrences[key]++
}
END {
    for (key in occurrences) {
        split(key, parts)
        print occurrences[key], parts[1], parts[2]
    }
}' apache-access.log | sort -nr
