#!/usr/bin/env bash
# script that displays the visitor IP along with the HTTP status code from the Apache log file
# awk '{print ++counter, $1, $9}' counter=0 apache-access.log
awk '{
    occurrence[++counter] = $0
}
END {
    for (i = counter; i >= 1; i--) {
        split(occurrence[i], parts)
        print i, parts[1], parts[9]
    }
}' counter=0 apache-access.log
