#!/usr/bin/env bash
# This script displays "Best School" 10 times but in the 9th time, it displays "Best School" and then "Hi"
# only while and if is permitted
counter=1
while [[ $counter -le 10 ]] ;
do
	echo "Best School"
	if [ $counter == 9 ]
	then
		echo "Hi"
	fi
	(( counter += 1 ))
done
