#!/usr/bin/env bash
# This scripts displays The content of the current directory In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)
# Using only while loop and not displaying hidden files
file="$(ls)"
for i in $file
do
	echo "${i#*-}"
done
