#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements

# Get the full path to the current user's home directory
# user_home=$HOME

# Create a copy of the hosts file
sudo cp /etc/hosts "$HOME/hosts.new"

# Use sed to modify the copy of the hosts file
sudo sed -i 's/127.0.0.1/127.0.0.2/' "$HOME/hosts.new"
echo '8.8.8.8	facebook.com' >> "$HOME/hosts.new"

# Overwrite the original hosts file with the modified copy
sudo cp -f  "$HOME/hosts.new" /etc/hosts
