#!/usr/bin/env bash
# script that displays all active IPv4 IPs on the machine it’s executed on.

# Use ifconfig to get active IPv4 IPs and filter the output with awk
ifconfig | awk '/inet / {print $2}'
