#!/usr/bin/env bash
# Script that makes Nginx run as the nginx user.

sed -i 's/^user.*/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/^    listen 80;/    listen 8080;/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2 || true

# Restart Nginx
/etc/init.d/nginx restart || nginx -s reload
