#!/usr/bin/env bash
# Script that makes Nginx run as the nginx user.
sed -i 's/^user.*/user nginx;/g' /etc/nginx/nginx.conf
sed -i '/^\s*server\s*{.*/a \\tlisten 8080 default_server;\n\tlisten [::]:8080 default_server;\n' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
/etc/init.d/nginx restart || nginx -s reload
