#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the
# private key ~/.ssh/school with the user ubuntu

# PRIVATE_KEY="$HOME/.ssh/school"
# USER="ubuntu"
# REMOTE_HOST=100.25.177.26
# ssh -i "$PRIVATE_KEY" "$USER@$REMOTE_HOST"

ssh -i ~/.ssh/school ubuntu@100.25.177.26
