#!/usr/bin/env bash

# Bash script that creates an RSA key pair
PRIVATE_KEY_NAME="school"
BITS=4096
PASSPHRASE="betty"

# Create RSA key pair
ssh-keygen -t rsa -b "$BITS" -f "$PRIVATE_KEY_NAME" -N "$PASSPHRASE"
